import Head from 'next/head';
import { DealCard } from '../components/Card/Card';
import { Grid, Title } from '@tremor/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>交通費を割り勘 Treat Driver</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='p-6 sm:p-10 h-screen'>
        <Title>Treat Driver</Title>

        <Grid numItemsMd={2} numItemsLg={4} className='gap-6 mt-6'>
          <DealCard title='test' start='海老名' end='名古屋' price={12345} />
        </Grid>
      </main>
    </>
  );
}
